#!/usr/bin/env python
import os
import sys
import numpy as np
import matplotlib.pylab as mpl
import argparse
import wxgen.util
import netCDF4
import shutil
import time
import datetime


def main():
    parser = argparse.ArgumentParser(description='Climate adjust all lead-times in a NetCDF database')
    parser.add_argument('file', help='NetCDF database')
    parser.add_argument('-o', type=str, help="Output file", dest="ofile", required=True)
    parser.add_argument('--debug', help='Show debug info', action="store_true")
    parser.add_argument('-g', help='Do calibration separately on each gridpoint?', dest="gridded", action="store_true")
    parser.add_argument('-lt', help='Which leadtimes to use for calibration?', dest="leadtimes")
    parser.add_argument('-v', help='Which variables to calibrate?', dest="variables")

    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(1)

    args = parser.parse_args()
    if args.file == args.ofile:
        wxgen.util.error("Input file must be different than the output file")


    shutil.copy(args.file, args.ofile)
    ifile = netCDF4.Dataset(args.file, 'r')
    # Which calibration function to use on each variable?
    var2func = {"air_temperature_2m": quantile_mapping,
          "precipitation_amount": quantile_mapping,
          "sea_level_pressure": multiplication,
          "cloud_area_fraction": addition,
          "x_wind_10m": multiplication,
          "y_wind_10m": multiplication}

    # Which variables to calibrate
    if args.variables is not None:
        vars = args.variables.split(',')
    else:
        vars = [var for var in ifile.variables if var not in ["latitude", "longitude", "time", "lead_time", "projection_regular_ll"]]

    # Write to output file
    leadtimes = ifile.variables["lead_time"][:]
    Ileadtimes = range(len(leadtimes))
    has_single_spatial_dim = "grid_point" in ifile.dimensions
    for var in vars:
        ofile = netCDF4.Dataset(args.ofile, 'a')
        print("Processing variable " + var)
        sys.stdout.flush()
        func = var2func[var]

        """
        For each leadtime, find the leadtime to use as reference. This will
        be the earliest leadtime for the same time of day.
        """
        Irefs = [np.where(leadtimes[i] % 24 == leadtimes % 24)[0][0] for i in Ileadtimes]

        """
        Gridded calibration: Apply a separate calibration on each grid point
        """
        if args.gridded:
            data = ifile.variables[var][:]
            # time, lead_time, ens, lat, lon
            if has_single_spatial_dim:
                G = data.shape[3]
            else:
                Y = data.shape[3]
                X = data.shape[4]
            print("Allocating %d GB" % (np.product(ofile.variables[var].shape) / 1024.0 / 1024.0 / 1024.0 * 4.0))
            q = np.zeros(ofile.variables[var].shape, float)

            if has_single_spatial_dim:
                for g in range(G):
                    for i in Ileadtimes:
                        Iref = Irefs[i]
                        if i == Iref:
                            # Don't calibrate if reference leadtime
                            q[:, i, :, g] = data[:, i, :, g]
                        else:
                            yy = np.sort(data[:, Iref, :, g].flatten())
                            xx = np.sort(data[:, i, :, g].flatten())
                            values = func(data[:, i, :, g].flatten(), xx, yy)

                            reshaped = np.reshape(values, [ofile.variables[var].shape[0], ofile.variables[var].shape[2]])
                            q[:, i, :, g] = reshaped[:]
            else:
                """
                It might be possible to parallelize x and y, but it requires some work
                to parallelize the calibration functions
                """
                for x in range(X):
                    for y in range(Y):
                        for i in Ileadtimes:
                            Iref = Irefs[i]
                            if i == Iref:
                                # Don't calibrate if reference leadtime
                                q[:, i, :, y, x] = data[:, i, :, y, x]
                            else:
                                yy = np.sort(data[:, Iref, :, y, x].flatten())
                                xx = np.sort(data[:, i, :, y, x].flat)
                                values = func(data[:, i, :, y, x].flat, xx, yy)

                                reshaped = np.reshape(values, [ofile.variables[var].shape[0], ofile.variables[var].shape[2]])
                                q[:, i, :, y, x] = reshaped
            ofile.variables[var][:] = q
        else:
            data = ifile.variables[var]
            for i in Ileadtimes:
                s = time.time()
                Iref = Irefs[i]
                if i == Iref:
                    ofile.variables[var][:, i, ...] = ifile.variables[var][:, i, ...]
                else:
                    dataref = data[:, Iref, ...]
                    xx = np.sort(data[:, i, ...].flatten())
                    yy = np.sort(dataref[:, ...].flatten())
                    values = func(ifile.variables[var][:, i, ...].flatten(), xx, yy)
                    shape = [size for size in ofile.variables[var].shape]
                    shape = [shape[j] for j in range(len(shape)) if j != 1]
                    reshaped = np.reshape(values, shape)
                    ofile.variables[var][:, i, ...] = reshaped[:]
        ofile.close()

    ofile = netCDF4.Dataset(args.ofile, 'a')

    # Add history string
    history_str = "%s Calibrated database:" % (datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S +00:00'))
    if args.gridded:
        history_str += " gridded"
    if hasattr(ifile, "history"):
        history_str = ifile.history + '\n' + history_str
    ofile.history = history_str

    ifile.close()
    ofile.close()


def addition(x, xx, yy):
    bias = np.mean(yy, dtype=np.float64) - np.mean(xx, dtype=np.float64)
    return x + bias


def multiplication(x, xx, yy):
    bias = np.mean(yy, dtype=np.float64) / np.mean(xx, dtype=np.float64)
    return x * bias


def quantile_mapping(x, xx, yy, min=None):
    """
    Arguments:
       x (np.array): x-axis values to interpolate to
       xx (np.array): x-axis control points
       yy (np.array): y-axis control points 
       min (float): Minimum value

    xx and yy must be sorted
   
    Returns:
       y (np.array): y-axis interpolated values
    """
    return np.interp(x, xx, yy)


if __name__ == "__main__":
    main()
