#!/usr/bin/env python
import os
import sys
import numpy as np
import matplotlib.pylab as mpl
import argparse
import verif.util
import netCDF


def main():
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('file', help='')

    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(1)

    args = parser.parse_args()


if __name__ == "__main__":
    main()
