#!/bin/bash
# Requires:
#   grib_filter from the grib_api package
#   fimex

idir=$1
fdir=$2
odir=$3
xmlfile=lee_GribReaderConfig.xml
#xmlfile=cdmGribReaderConfigEC_MAD.xml

# Splits grib files into single files by forecast initialization date
for file in `ls $idir/????????_*.grb`; do
   echo "Filtering $file"
   date=$(basename -- "$file")
   date=`echo $date | cut -d'_' -f 1`.nc
   date="${date%.*}"
   files=$idir/${date}_*.grb
   echo $files
   grib_filter rules_file $files
done

# Convert to netcdf
for file in `ls $fdir/*.grb`; do
   echo "Converting $file"
   temp=$(basename -- "$file")
   ofile=$odir/`echo $temp | cut -d'.' -f 1`.nc
   fimex $file $ofile --input.config $xmlfile --output.type nc
done
